title: "Go プログラミングノート"
summary: "Go を学習するに当たり学んだことを記述していく"
topics: ["go", "golang", "tutorial"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - memo # メモ
  - return-greetings-for-multiple-people # https://go.dev/doc/tutorial/greetings-multiple-people
  - install
  - example-gin
  - orm-json
