on:
  pull_request:
    types: [opened]
name: Pull Request
permissions:
  issues: write
  pull-requests: write
  repository-projects: read
jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
