on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
  repository-projects: read
name: Pull Request
jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1

